### PR TITLE
Various Improvements by BejoIjo (Dec 8 2017)

### PR DESCRIPTION
**Pull request by BejoIjo**
Improvements includes:
- All the improvements from previous PR
- Replaced SQLite with LiteDB (for more lightweight and stable)
- Randomly generated citation history based on citation counts
- Randomly generated past arrest reports if ped wanted (with probability)
- Replace ComputerPedView implementation to make it more stable
- Made several fixes on Form components and layout adjustments

### CODE REVIEW

**Comment by ainesophaur** [comment]
Since this is your active branch I'll make my suggestions here.

One thing to add is the config file addition for enabling/disabling randomly generated citations and arrests. While 90% of the players will certainly appreciate it, there are some that wont. Put in an option in the config class and set a default by code. Optionally, add an in game prompt/warning if they are missing the config value (just so we dont get tons of support requests/complaints on how to change it)

Im pulling this branch down for testing. Is it stable enough for me to test now or do you have pending/uncommitted work?

**Comment by BejoIjo** [comment]
Yes, this is the latest one. you may test it.
BTW. you will only need to put LiteDB.dll in the main GTA V folder to make it works. (no need for any interop library)

Regarding configuration for randomly generated arrest report & citation, that's a good Idea. I'll add it early on tomorrow.

**Comment by BejoIjo** [comment]
here you go, the latest commit with configuration flag to disable/enable random historical Arrest Reports and Traffic citations.

**Comment by smithrn99** [comment]
Copied from forum:

> Great update! However, I noticed two bugs.
> 1. The DoB bug (missing zeroes) is still present.  "1/4/1997" should correct to "01/04/1997" etc to prevent errors when writing citations/arrest reports.
> 2. The randomized citations all show a SHERIFF2 as the vehicle.

**Comment by BejoIjo** [comment]
i pushed the potential fix. please try it out when the author release it.

**Comment by BejoIjo** [comment]
I guess that's it for now and the next release. Everything should be good (y)

**Comment by BejoIjo** [comment]
Ready for release. Engage!

**Comment by ainesophaur** [comment]
I'll pull it, build and release it tomorrow.

**Comment by ainesophaur** [comment]
Released to LSPDFR

**Pull request merged**
