### PR TITLE
Various improvements by BejoIjo (initial)

### PR DESCRIPTION
**Pull request by BejoIjo**
List of improvements:
- previous arrest report & citation will be displayed when viewing ped/vehicle info (without crashing)
- reactivated traffic citation history
- reactivated arrest report history
- reactivated most recent action list on main window
- added wanted reason info when ped is wanted
- added proper db index for TrafficCitation table (bump the storage version to 1.0.2)
- made ped & vehicle persistent during C+ session to avoid crashes (they will be freed when Computer+ exit)
- saving newly created arrest report or citation will also close the window for better UX
- vehicle type will be showed correctly when viewing the citation history records
- fixed "give ticket" animation. now the ticket should disappear in the right time
- added driver license expiration days info (random)
- fixed incorrect time data source on arrest report view
- added various checking and handling to prevent potential crashes.

It's very stable on my machine, but still needs to be tested by other users, since i don't use alpr plugin and british policing plugin.

To test it, make sure to overwrite all C+ files/folders on your LSPDFR plugins folder. You may keep your old ".ini" file since there's no changes on that part.

### CODE REVIEW

**Comment by ainesophaur** [comment]
I'll check it out tomorrow and see how everything works. I appreciate the assistance in knocking this out.

**Comment by ainesophaur** [comment]
@bejoljo

The current issue with my code base in relation to previous arrests was the sql joining query. 

In order to properly test it, you would have to pull over a ped and get their name and dob (do not create a citation, use the regular lspdfr functions to discover the Ped's info)  Then use a sql browser for sql lite and then modify an old arrest to match the newly discovered ped. Then use Computer + to look up the ped and browse any old citations.

The issue I've come across previously  is the sql join returns a null value each time. If you create a new citation for a ped it will always show that citation because it's in memory and it doesn't have to query sql.. But once it has to query sql, it dies.

If you're able to replicate the test and return results with no crashes then I can move forward with cherry picking the merge. I plan on reviewing your contribution on Saturday

**Comment by BejoIjo** [comment]
> The issue I've come across previously is the sql join returns a null value each time. If you create a new citation for a ped it will always show that citation because it's in memory and it doesn't have to query sql.. But once it has to query sql, it dies.

Yes, my PR already contains fix for this issue.
- I pulled over a suspect and create citation or arrest report
- Then I close/logout the C+
- I open C+ again and select the same ped from the list (which will trigger sql queries)
- I can see the citation or arrest report contents from the ones that i previously created

I can do that several times with different peds & different pull overs withour crashing.

Please try it for yourself. If you don't have time to pull and compile it, I can send you the .dll file.

**Comment by ainesophaur** [comment]
If I recall correctly, I save a reference to the Ped and I have a property
whether it already has a populated list of citations. So writing a report,
closing out and pulling the same ped over before they get recycled wouldn't
trigger the crash.

From what I remember, the crashing comes when it's the first lookup of a
ped and there are sql results to convert to the appropriate report type.

Unfortunately it's been over half a year since I worked it and I'm a bit
foggy on how I could replicate the crash on demand. I know I just commented
out the sql lookup to stop the crashing.

If possible, please try my suggested test. Stop a ped and get their info.
Pause the game and edit the sql db for a previous arrest of a different
ped. Edit the row to match the ped you stopped. Then when you go back in
game, lookup the ped for the first time in Computer +. If it shows the
arrest report then you've solved the issue.

I'm pretty excited to test this. You can certainly add the binary dll in a
git commit on your fork and save me some time. You don't have to worry
about appending it to the pull request.

**Comment by BejoIjo** [comment]
Hi there,

I tested it and works. please find the screenshots.
please note that there's 1 day discrepancy on the DOB since you save it as string in locale time zone and the one coming from LSPDFR traffic stop is in UTC i guess. I'm in PST and it's night time right here and the GMT is already one day ahead.

1. get driver license info from traffic stop


2. edit citation & arrest report from old records and replace it with the current pulled over ped first, second, amd DOB
sql1
sql2

3. open C+ and the old reports correctly linked to the pulled over ped.

**Comment by ainesophaur** [comment]
Bang up job. The community is going to love your contribution. I'll see if
Pie or someone else can review your dll. If all checks out I'll do a final
once over on the code and release it. Is your username on LSPDFR the same
as here?

**Comment by BejoIjo** [comment]
Thanks. I did it for LSPDFR community who already provided so many awesome mods for us.

> From Player - By Player - For Players  :)

BTW. I've uploaded the compiled .dll file and 1 schema file: 
https://drive.google.com/file/d/1-GA-8BBg4X8UdftJ0GNDahp5C14SJm1p/view?usp=sharing

Please make sure to put the 1.0.2.sql file inside the "**plugins\LSPDFR\ComputerPlus\Schemas**" folder.
I added proper index for TrafficCitation table, so it won't get slowed down when the content is getting bigger.

**Comment by ainesophaur** [comment]
Hey @BejoIjo just letting you know that I've pulled the fork and I'm compiling and testing it now.

**Comment by BejoIjo** [comment]
Hi @ainesophaur,

Glad you're back. In the past 12 days, I made more improvements based on this branch.
You can find it in this PR: https://github.com/PieRGud/ComputerPlus/pull/34

BR.

**Pull request merged**
